sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  include:
    - os: osx
      language: generic
      env:
        - TOXENV=py27
        - BREW_INSTALL=python
    - os: osx
      language: generic
      env:
        - TOXENV=py36
        - BREW_INSTALL=python3

install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      if [[ -n "$BREW_INSTALL" ]]; then
        brew update
        brew install "$BREW_INSTALL"
      fi
      sudo pip install tox
    fi
  - pip install tox-travis

script: tox
