environment:
  matrix:
    - PYTHON: "C:/Python27"
    - PYTHON: "C:/Python34"
    - PYTHON: "C:/Python35"
    - PYTHON: "C:/Python36"
    - PYTHON: "C:/Python27-x64"
    - PYTHON: "C:/Python34-x64"
    - PYTHON: "C:/Python35-x64"
    - PYTHON: "C:/Python36-x64"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install --upgrade wheel setuptools"
  - "pip install cython future"
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

build: off

test_script:
  - "python setup.py test"

after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
  - name: dist
